pip install aiohttp
pip install aiosignal
pip install anyio
pip install async-timeout
pip install attrs
pip install certifi
pip install charset-normalizer
pip install colorama
pip install dropbox
pip install exceptiongroup
pip install ffmpeg-python
pip install frozenlist
pip install idna
pip install jgtapy
pip install multidict
pip install numpy
pip install packaging
pip install pandas
pip install ply
pip install python-dateutil
pip install python-dotenv
pip install pytz
pip install PyYAML
pip install requests
pip install six
pip install sniffio
pip install stone
pip install tlid
pip install tqdm
pip install tzdata
pip install urllib3
pip install yarl
